module.exports = [
  { name: 'Introdução ao React', school: 'Rocketseat', dateEnd: 'conclusão em 2021.' },
  { name: 'Javascript ES6', school: 'Rocketseat', dateEnd: 'conclusão em 2021.' },
  { name: 'Rest com NodeJS: API com Express e Mysql', school: 'Alura', dateEnd: 'conclusão 2021.' },
  { name: 'JAVA Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.' },
  { name: 'JAVA POO, Curso em Vídeo', school: 'Curso em Vídeo', dateEnd: 'conclusão em 2019.' },
  { name: 'JAVA para Iniciantes, Curso em Vídeo', school: 'Curso em Vídeo', dateEnd: 'conclusão em 2019.' },
  { name: 'Javascript Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.' },
  { name: 'CSS3 Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.' },
  { name: 'JQuery Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.' },
  { name: 'PHP Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.' },
  { name: 'SQL Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2017.' },
  { name: 'HTML5 Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2018.' },
  { name: 'C++ Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.' },
  { name: 'Ruby Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2018.' },
  { name: 'Inglês básico', school: 'CNA', dateEnd: 'conclusão em 2011.' },
  { name: 'Montagem e Manutenção de Microcomputadores', school: 'INTEP', dateEnd: 'conclusão em 2015.' },
  { name: 'HTML4', school: 'Center News', dateEnd: 'conclusão em 2009.' },
  { name: 'Montagem e Manutenção de Microcomputadores', school: 'Remington', dateEnd: 'conclusão em 2009.' },
  { name: 'Curso de Informática básica (Pacote Office, Win XP, CorelDraw)', school: 'Franca Informática', dateEnd: 'conclusão em 2009.' }
]