module.exports = [
  { name: 'Introdução ao React', school: 'Rocketseat', dateEnd: 'conclusão em 2021.', icon: 'fab fa-react' },
  { name: 'Javascript ES6', school: 'Rocketseat', dateEnd: 'conclusão em 2021.', icon: 'fab fa-js' },
  { name: 'Rest com NodeJS: API com Express e Mysql', school: 'Alura', dateEnd: 'conclusão 2021.', icon: 'fab fa-node' },
  { name: 'JAVA Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: 'fab fa-java' },
  { name: 'JAVA POO, Curso em Vídeo', school: 'Curso em Vídeo', dateEnd: 'conclusão em 2019.', icon: 'fab fa-java' },
  { name: 'JAVA para Iniciantes, Curso em Vídeo', school: 'Curso em Vídeo', dateEnd: 'conclusão em 2019.', icon: 'fab fa-java' },
  { name: 'Javascript Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: 'fab fa-js' },
  { name: 'CSS3 Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: 'fab fa-css3' },
  { name: 'JQuery Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: 'fab fa-js' },
  { name: 'PHP Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: 'fab fa-php' },
  { name: 'SQL Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2017.', icon: 'fas fa-database' },
  { name: 'HTML5 Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2018.', icon: 'fab fa-html5' },
  { name: 'C++ Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: 'fas fa-code' },
  { name: 'Ruby Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2018.' , icon: 'fas fa-code'},
  { name: 'Inglês básico', school: 'CNA', dateEnd: 'conclusão em 2011.', icon: 'fas fa-comments' },
  { name: 'Montagem e Manutenção de Microcomputadores', school: 'INTEP', dateEnd: 'conclusão em 2015.', icon: 'fas fa-microchip'},
  { name: 'HTML4', school: 'Center News', dateEnd: 'conclusão em 2009.', icon: 'fas fa-file-code' },
  { name: 'Montagem e Manutenção de Microcomputadores', school: 'Remington', dateEnd: 'conclusão em 2009.' , icon: 'fas fa-tools'},
  { name: 'Curso de Informática básica (Pacote Office, Win XP, CorelDraw)', school: 'Franca Informática', dateEnd: 'conclusão em 2009.', icon: 'fas fa-laptop-code' }
]