module.exports = [
  { name: 'Introdução ao React', school: 'Rocketseat', dateEnd: 'conclusão em 2021.', icon: ' ' },
  { name: 'Javascript ES6', school: 'Rocketseat', dateEnd: 'conclusão em 2021.', icon: ' ' },
  { name: 'Rest com NodeJS: API com Express e Mysql', school: 'Alura', dateEnd: 'conclusão 2021.', icon: ' ' },
  { name: 'JAVA Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: ' ' },
  { name: 'JAVA POO, Curso em Vídeo', school: 'Curso em Vídeo', dateEnd: 'conclusão em 2019.', icon: ' ' },
  { name: 'JAVA para Iniciantes, Curso em Vídeo', school: 'Curso em Vídeo', dateEnd: 'conclusão em 2019.', icon: '' },
  { name: 'Javascript Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: '' },
  { name: 'CSS3 Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: 'fab fa-css3' },
  { name: 'JQuery Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: ' ' },
  { name: 'PHP Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: ' ' },
  { name: 'SQL Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2017.', icon: ' ' },
  { name: 'HTML5 Fundamentals Course', school: 'Sololearn', dateEnd: 'conclusão em 2018.', icon: ' ' },
  { name: 'C++ Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2019.', icon: ' ' },
  { name: 'Ruby Tutorial Course', school: 'Sololearn', dateEnd: 'conclusão em 2018.' , icon: ' '},
  { name: 'Inglês básico', school: 'CNA', dateEnd: 'conclusão em 2011.', icon: ' ' },
  { name: 'Montagem e Manutenção de Microcomputadores', school: 'INTEP', dateEnd: 'conclusão em 2015.', icon: ' '},
  { name: 'HTML4', school: 'Center News', dateEnd: 'conclusão em 2009.', icon: ' ' },
  { name: 'Montagem e Manutenção de Microcomputadores', school: 'Remington', dateEnd: 'conclusão em 2009.' , icon: ' '},
  { name: 'Curso de Informática básica (Pacote Office, Win XP, CorelDraw)', school: 'Franca Informática', dateEnd: 'conclusão em 2009.', icon: ' ' }
]